"
A simple application that keeps track of a bunch of friends named Fred that like to share lunches together.
They do this regularly and they like to keep a single check so we take turns paying the bill.
For each lunch we track who eats and does not pay, and who eats and pays. 
The end result is a number for each fred.  The friend with the highest number gets to pay if he is able.
"
Class {
	#name : #ManifestFredsLunch,
	#superclass : #PackageManifest,
	#category : #'FredsLunch-Manifest'
}
